// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> FlutterError {
  return FlutterError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum BleRole: Int {
  case central = 0
  case peripheral = 1
}

enum BleAdapterState: Int {
  case unknown = 0
  case unsupported = 1
  case unauthorized = 2
  case poweredOff = 3
  case poweredOn = 4
}

enum BlePathState: Int {
  case discovered = 0
  case connecting = 1
  case connected = 2
  case subscribed = 3
  case ready = 4
  case stale = 5
  case disconnected = 6
  case failed = 7
}

enum BleWriteMode: Int {
  case withoutResponse = 0
  case withResponse = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleInitializeOptions {
  var showPowerAlert: Bool
  var restoreState: Bool
  var verboseLogging: Bool

  static func fromList(_ list: [Any?]) -> BleInitializeOptions? {
    let showPowerAlert = list[0] as! Bool
    let restoreState = list[1] as! Bool
    let verboseLogging = list[2] as! Bool

    return BleInitializeOptions(
      showPowerAlert: showPowerAlert,
      restoreState: restoreState,
      verboseLogging: verboseLogging
    )
  }
  func toList() -> [Any?] {
    return [
      showPowerAlert,
      restoreState,
      verboseLogging,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleAdvertiseRequest {
  var serviceUuid: String
  var characteristicUuid: String
  var localName: String? = nil
  var includeDeviceName: Bool
  var bondless: Bool
  var manufacturerId: Int64? = nil
  var manufacturerData: FlutterStandardTypedData? = nil

  static func fromList(_ list: [Any?]) -> BleAdvertiseRequest? {
    let serviceUuid = list[0] as! String
    let characteristicUuid = list[1] as! String
    let localName: String? = nilOrValue(list[2])
    let includeDeviceName = list[3] as! Bool
    let bondless = list[4] as! Bool
    let manufacturerId: Int64? = isNullish(list[5]) ? nil : (list[5] is Int64? ? list[5] as! Int64? : Int64(list[5] as! Int32))
    let manufacturerData: FlutterStandardTypedData? = nilOrValue(list[6])

    return BleAdvertiseRequest(
      serviceUuid: serviceUuid,
      characteristicUuid: characteristicUuid,
      localName: localName,
      includeDeviceName: includeDeviceName,
      bondless: bondless,
      manufacturerId: manufacturerId,
      manufacturerData: manufacturerData
    )
  }
  func toList() -> [Any?] {
    return [
      serviceUuid,
      characteristicUuid,
      localName,
      includeDeviceName,
      bondless,
      manufacturerId,
      manufacturerData,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleScanRequest {
  var serviceUuidPrefix: String? = nil
  var serviceUuids: [String?]
  var timeoutMs: Int64
  var allowDuplicates: Bool
  var androidScanMode: Int64

  static func fromList(_ list: [Any?]) -> BleScanRequest? {
    let serviceUuidPrefix: String? = nilOrValue(list[0])
    let serviceUuids = list[1] as! [String?]
    let timeoutMs = list[2] is Int64 ? list[2] as! Int64 : Int64(list[2] as! Int32)
    let allowDuplicates = list[3] as! Bool
    let androidScanMode = list[4] is Int64 ? list[4] as! Int64 : Int64(list[4] as! Int32)

    return BleScanRequest(
      serviceUuidPrefix: serviceUuidPrefix,
      serviceUuids: serviceUuids,
      timeoutMs: timeoutMs,
      allowDuplicates: allowDuplicates,
      androidScanMode: androidScanMode
    )
  }
  func toList() -> [Any?] {
    return [
      serviceUuidPrefix,
      serviceUuids,
      timeoutMs,
      allowDuplicates,
      androidScanMode,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleConnectRequest {
  var remoteId: String
  var serviceUuid: String
  var characteristicUuid: String
  var timeoutMs: Int64
  var subscribeToNotifications: Bool
  var androidMtu: Int64? = nil

  static func fromList(_ list: [Any?]) -> BleConnectRequest? {
    let remoteId = list[0] as! String
    let serviceUuid = list[1] as! String
    let characteristicUuid = list[2] as! String
    let timeoutMs = list[3] is Int64 ? list[3] as! Int64 : Int64(list[3] as! Int32)
    let subscribeToNotifications = list[4] as! Bool
    let androidMtu: Int64? = isNullish(list[5]) ? nil : (list[5] is Int64? ? list[5] as! Int64? : Int64(list[5] as! Int32))

    return BleConnectRequest(
      remoteId: remoteId,
      serviceUuid: serviceUuid,
      characteristicUuid: characteristicUuid,
      timeoutMs: timeoutMs,
      subscribeToNotifications: subscribeToNotifications,
      androidMtu: androidMtu
    )
  }
  func toList() -> [Any?] {
    return [
      remoteId,
      serviceUuid,
      characteristicUuid,
      timeoutMs,
      subscribeToNotifications,
      androidMtu,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleSendRequest {
  var pathId: String
  var value: FlutterStandardTypedData
  var writeMode: BleWriteMode

  static func fromList(_ list: [Any?]) -> BleSendRequest? {
    let pathId = list[0] as! String
    let value = list[1] as! FlutterStandardTypedData
    let writeMode = BleWriteMode(rawValue: list[2] as! Int)!

    return BleSendRequest(
      pathId: pathId,
      value: value,
      writeMode: writeMode
    )
  }
  func toList() -> [Any?] {
    return [
      pathId,
      value,
      writeMode.rawValue,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleDisconnectRequest {
  var pathId: String
  var forget: Bool

  static func fromList(_ list: [Any?]) -> BleDisconnectRequest? {
    let pathId = list[0] as! String
    let forget = list[1] as! Bool

    return BleDisconnectRequest(
      pathId: pathId,
      forget: forget
    )
  }
  func toList() -> [Any?] {
    return [
      pathId,
      forget,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BleAdvertisement {
  var remoteId: String
  var platformName: String? = nil
  var advertisedName: String? = nil
  var serviceUuids: [String?]
  var rssi: Int64
  var connectable: Bool
  var txPower: Int64? = nil
  var manufacturerData: FlutterStandardTypedData? = nil

  static func fromList(_ list: [Any?]) -> BleAdvertisement? {
    let remoteId = list[0] as! String
    let platformName: String? = nilOrValue(list[1])
    let advertisedName: String? = nilOrValue(list[2])
    let serviceUuids = list[3] as! [String?]
    let rssi = list[4] is Int64 ? list[4] as! Int64 : Int64(list[4] as! Int32)
    let connectable = list[5] as! Bool
    let txPower: Int64? = isNullish(list[6]) ? nil : (list[6] is Int64? ? list[6] as! Int64? : Int64(list[6] as! Int32))
    let manufacturerData: FlutterStandardTypedData? = nilOrValue(list[7])

    return BleAdvertisement(
      remoteId: remoteId,
      platformName: platformName,
      advertisedName: advertisedName,
      serviceUuids: serviceUuids,
      rssi: rssi,
      connectable: connectable,
      txPower: txPower,
      manufacturerData: manufacturerData
    )
  }
  func toList() -> [Any?] {
    return [
      remoteId,
      platformName,
      advertisedName,
      serviceUuids,
      rssi,
      connectable,
      txPower,
      manufacturerData,
    ]
  }
}

/// A role-tagged BLE link. The `pathId` is the only stable handle the
/// application should use to address a path. It has the form
/// `central:<opaque>` or `peripheral:<opaque>`. The portion after the colon
/// is the platform's view of the remote (CBPeripheral.identifier on iOS, the
/// Bluetooth address on Android) — treat it as opaque, do not parse it, and
/// do not assume it is stable across reconnects or app restarts.
///
/// Generated class from Pigeon that represents data sent in messages.
struct BlePath {
  var pathId: String
  var role: BleRole
  var state: BlePathState
  var platformDeviceId: String? = nil
  var serviceUuid: String? = nil
  var characteristicUuid: String? = nil
  var rssi: Int64
  var mtu: Int64
  var canSend: Bool
  var error: String? = nil

  static func fromList(_ list: [Any?]) -> BlePath? {
    let pathId = list[0] as! String
    let role = BleRole(rawValue: list[1] as! Int)!
    let state = BlePathState(rawValue: list[2] as! Int)!
    let platformDeviceId: String? = nilOrValue(list[3])
    let serviceUuid: String? = nilOrValue(list[4])
    let characteristicUuid: String? = nilOrValue(list[5])
    let rssi = list[6] is Int64 ? list[6] as! Int64 : Int64(list[6] as! Int32)
    let mtu = list[7] is Int64 ? list[7] as! Int64 : Int64(list[7] as! Int32)
    let canSend = list[8] as! Bool
    let error: String? = nilOrValue(list[9])

    return BlePath(
      pathId: pathId,
      role: role,
      state: state,
      platformDeviceId: platformDeviceId,
      serviceUuid: serviceUuid,
      characteristicUuid: characteristicUuid,
      rssi: rssi,
      mtu: mtu,
      canSend: canSend,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      pathId,
      role.rawValue,
      state.rawValue,
      platformDeviceId,
      serviceUuid,
      characteristicUuid,
      rssi,
      mtu,
      canSend,
      error,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BlePayload {
  var pathId: String
  var role: BleRole
  var value: FlutterStandardTypedData
  var rssi: Int64

  static func fromList(_ list: [Any?]) -> BlePayload? {
    let pathId = list[0] as! String
    let role = BleRole(rawValue: list[1] as! Int)!
    let value = list[2] as! FlutterStandardTypedData
    let rssi = list[3] is Int64 ? list[3] as! Int64 : Int64(list[3] as! Int32)

    return BlePayload(
      pathId: pathId,
      role: role,
      value: value,
      rssi: rssi
    )
  }
  func toList() -> [Any?] {
    return [
      pathId,
      role.rawValue,
      value,
      rssi,
    ]
  }
}
private class GrassrootsBluetoothLayerHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return BleAdvertiseRequest.fromList(self.readValue() as! [Any?])
    case 129:
      return BleConnectRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return BleDisconnectRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return BleInitializeOptions.fromList(self.readValue() as! [Any?])
    case 132:
      return BlePath.fromList(self.readValue() as! [Any?])
    case 133:
      return BlePath.fromList(self.readValue() as! [Any?])
    case 134:
      return BleScanRequest.fromList(self.readValue() as! [Any?])
    case 135:
      return BleSendRequest.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class GrassrootsBluetoothLayerHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BleAdvertiseRequest {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? BleConnectRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? BleDisconnectRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? BleInitializeOptions {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? BlePath {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? BlePath {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? BleScanRequest {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? BleSendRequest {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class GrassrootsBluetoothLayerHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return GrassrootsBluetoothLayerHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return GrassrootsBluetoothLayerHostApiCodecWriter(data: data)
  }
}

class GrassrootsBluetoothLayerHostApiCodec: FlutterStandardMessageCodec {
  static let shared = GrassrootsBluetoothLayerHostApiCodec(readerWriter: GrassrootsBluetoothLayerHostApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol GrassrootsBluetoothLayerHostApi {
  func initialize(options: BleInitializeOptions) throws
  func isSupported() throws -> Bool
  func adapterState() throws -> BleAdapterState
  func startAdvertising(request: BleAdvertiseRequest) throws
  func stopAdvertising() throws
  func startScan(request: BleScanRequest) throws
  func stopScan() throws
  func connect(request: BleConnectRequest) throws -> BlePath
  func disconnect(request: BleDisconnectRequest) throws
  func send(request: BleSendRequest) throws
  func paths() throws -> [BlePath]
  func dispose() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class GrassrootsBluetoothLayerHostApiSetup {
  /// The codec used by GrassrootsBluetoothLayerHostApi.
  static var codec: FlutterStandardMessageCodec { GrassrootsBluetoothLayerHostApiCodec.shared }
  /// Sets up an instance of `GrassrootsBluetoothLayerHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: GrassrootsBluetoothLayerHostApi?) {
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.initialize", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! BleInitializeOptions
        do {
          try api.initialize(options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    let isSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.isSupported", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isSupportedChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isSupported()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isSupportedChannel.setMessageHandler(nil)
    }
    let adapterStateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.adapterState", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      adapterStateChannel.setMessageHandler { _, reply in
        do {
          let result = try api.adapterState()
          reply(wrapResult(result.rawValue))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      adapterStateChannel.setMessageHandler(nil)
    }
    let startAdvertisingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.startAdvertising", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAdvertisingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! BleAdvertiseRequest
        do {
          try api.startAdvertising(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startAdvertisingChannel.setMessageHandler(nil)
    }
    let stopAdvertisingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.stopAdvertising", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopAdvertisingChannel.setMessageHandler { _, reply in
        do {
          try api.stopAdvertising()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopAdvertisingChannel.setMessageHandler(nil)
    }
    let startScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.startScan", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startScanChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! BleScanRequest
        do {
          try api.startScan(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startScanChannel.setMessageHandler(nil)
    }
    let stopScanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.stopScan", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopScanChannel.setMessageHandler { _, reply in
        do {
          try api.stopScan()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      stopScanChannel.setMessageHandler(nil)
    }
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.connect", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! BleConnectRequest
        do {
          let result = try api.connect(request: requestArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.disconnect", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! BleDisconnectRequest
        do {
          try api.disconnect(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let sendChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.send", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! BleSendRequest
        do {
          try api.send(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendChannel.setMessageHandler(nil)
    }
    let pathsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.paths", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pathsChannel.setMessageHandler { _, reply in
        do {
          let result = try api.paths()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      pathsChannel.setMessageHandler(nil)
    }
    let disposeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.dispose", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disposeChannel.setMessageHandler { _, reply in
        do {
          try api.dispose()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disposeChannel.setMessageHandler(nil)
    }
  }
}
private class GrassrootsBluetoothLayerFlutterApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 128:
      return BleAdvertisement.fromList(self.readValue() as! [Any?])
    case 129:
      return BlePath.fromList(self.readValue() as! [Any?])
    case 130:
      return BlePayload.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class GrassrootsBluetoothLayerFlutterApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BleAdvertisement {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? BlePath {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? BlePayload {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class GrassrootsBluetoothLayerFlutterApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return GrassrootsBluetoothLayerFlutterApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return GrassrootsBluetoothLayerFlutterApiCodecWriter(data: data)
  }
}

class GrassrootsBluetoothLayerFlutterApiCodec: FlutterStandardMessageCodec {
  static let shared = GrassrootsBluetoothLayerFlutterApiCodec(readerWriter: GrassrootsBluetoothLayerFlutterApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol GrassrootsBluetoothLayerFlutterApiProtocol {
  func onAdapterStateChanged(state stateArg: BleAdapterState, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onAdvertisement(advertisement advertisementArg: BleAdvertisement, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onPathChanged(path pathArg: BlePath, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onPayloadReceived(payload payloadArg: BlePayload, completion: @escaping (Result<Void, FlutterError>) -> Void)
  func onLog(message messageArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void)
}
class GrassrootsBluetoothLayerFlutterApi: GrassrootsBluetoothLayerFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger) {
    self.binaryMessenger = binaryMessenger
  }
  var codec: FlutterStandardMessageCodec {
    return GrassrootsBluetoothLayerFlutterApiCodec.shared
  }
  func onAdapterStateChanged(state stateArg: BleAdapterState, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerFlutterApi.onAdapterStateChanged"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([stateArg.rawValue] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onAdvertisement(advertisement advertisementArg: BleAdvertisement, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerFlutterApi.onAdvertisement"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([advertisementArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onPathChanged(path pathArg: BlePath, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerFlutterApi.onPathChanged"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([pathArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onPayloadReceived(payload payloadArg: BlePayload, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerFlutterApi.onPayloadReceived"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([payloadArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onLog(message messageArg: String, completion: @escaping (Result<Void, FlutterError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerFlutterApi.onLog"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([messageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
