// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package org.permissionlesstech.grassroots_bluetooth_layer

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class BleRole(val raw: Int) {
  CENTRAL(0),
  PERIPHERAL(1);

  companion object {
    fun ofRaw(raw: Int): BleRole? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleAdapterState(val raw: Int) {
  UNKNOWN(0),
  UNSUPPORTED(1),
  UNAUTHORIZED(2),
  POWERED_OFF(3),
  POWERED_ON(4);

  companion object {
    fun ofRaw(raw: Int): BleAdapterState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BlePathState(val raw: Int) {
  DISCOVERED(0),
  CONNECTING(1),
  CONNECTED(2),
  SUBSCRIBED(3),
  READY(4),
  STALE(5),
  DISCONNECTED(6),
  FAILED(7);

  companion object {
    fun ofRaw(raw: Int): BlePathState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BleWriteMode(val raw: Int) {
  WITHOUT_RESPONSE(0),
  WITH_RESPONSE(1);

  companion object {
    fun ofRaw(raw: Int): BleWriteMode? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleInitializeOptions (
  val showPowerAlert: Boolean,
  val restoreState: Boolean,
  val verboseLogging: Boolean

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): BleInitializeOptions {
      val showPowerAlert = list[0] as Boolean
      val restoreState = list[1] as Boolean
      val verboseLogging = list[2] as Boolean
      return BleInitializeOptions(showPowerAlert, restoreState, verboseLogging)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      showPowerAlert,
      restoreState,
      verboseLogging,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleAdvertiseRequest (
  val serviceUuid: String,
  val characteristicUuid: String,
  val localName: String? = null,
  val includeDeviceName: Boolean,
  val bondless: Boolean,
  val manufacturerId: Long? = null,
  val manufacturerData: ByteArray? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): BleAdvertiseRequest {
      val serviceUuid = list[0] as String
      val characteristicUuid = list[1] as String
      val localName = list[2] as String?
      val includeDeviceName = list[3] as Boolean
      val bondless = list[4] as Boolean
      val manufacturerId = list[5].let { if (it is Int) it.toLong() else it as Long? }
      val manufacturerData = list[6] as ByteArray?
      return BleAdvertiseRequest(serviceUuid, characteristicUuid, localName, includeDeviceName, bondless, manufacturerId, manufacturerData)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      serviceUuid,
      characteristicUuid,
      localName,
      includeDeviceName,
      bondless,
      manufacturerId,
      manufacturerData,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleScanRequest (
  val serviceUuidPrefix: String? = null,
  val serviceUuids: List<String?>,
  val timeoutMs: Long,
  val allowDuplicates: Boolean,
  val androidScanMode: Long

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): BleScanRequest {
      val serviceUuidPrefix = list[0] as String?
      val serviceUuids = list[1] as List<String?>
      val timeoutMs = list[2].let { if (it is Int) it.toLong() else it as Long }
      val allowDuplicates = list[3] as Boolean
      val androidScanMode = list[4].let { if (it is Int) it.toLong() else it as Long }
      return BleScanRequest(serviceUuidPrefix, serviceUuids, timeoutMs, allowDuplicates, androidScanMode)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      serviceUuidPrefix,
      serviceUuids,
      timeoutMs,
      allowDuplicates,
      androidScanMode,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleConnectRequest (
  val remoteId: String,
  val serviceUuid: String,
  val characteristicUuid: String,
  val timeoutMs: Long,
  val subscribeToNotifications: Boolean,
  val androidMtu: Long? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): BleConnectRequest {
      val remoteId = list[0] as String
      val serviceUuid = list[1] as String
      val characteristicUuid = list[2] as String
      val timeoutMs = list[3].let { if (it is Int) it.toLong() else it as Long }
      val subscribeToNotifications = list[4] as Boolean
      val androidMtu = list[5].let { if (it is Int) it.toLong() else it as Long? }
      return BleConnectRequest(remoteId, serviceUuid, characteristicUuid, timeoutMs, subscribeToNotifications, androidMtu)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      remoteId,
      serviceUuid,
      characteristicUuid,
      timeoutMs,
      subscribeToNotifications,
      androidMtu,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleSendRequest (
  val pathId: String,
  val value: ByteArray,
  val writeMode: BleWriteMode

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): BleSendRequest {
      val pathId = list[0] as String
      val value = list[1] as ByteArray
      val writeMode = BleWriteMode.ofRaw(list[2] as Int)!!
      return BleSendRequest(pathId, value, writeMode)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      pathId,
      value,
      writeMode.raw,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleDisconnectRequest (
  val pathId: String,
  val forget: Boolean

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): BleDisconnectRequest {
      val pathId = list[0] as String
      val forget = list[1] as Boolean
      return BleDisconnectRequest(pathId, forget)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      pathId,
      forget,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BleAdvertisement (
  val remoteId: String,
  val platformName: String? = null,
  val advertisedName: String? = null,
  val serviceUuids: List<String?>,
  val rssi: Long,
  val connectable: Boolean,
  val txPower: Long? = null,
  val manufacturerData: ByteArray? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): BleAdvertisement {
      val remoteId = list[0] as String
      val platformName = list[1] as String?
      val advertisedName = list[2] as String?
      val serviceUuids = list[3] as List<String?>
      val rssi = list[4].let { if (it is Int) it.toLong() else it as Long }
      val connectable = list[5] as Boolean
      val txPower = list[6].let { if (it is Int) it.toLong() else it as Long? }
      val manufacturerData = list[7] as ByteArray?
      return BleAdvertisement(remoteId, platformName, advertisedName, serviceUuids, rssi, connectable, txPower, manufacturerData)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      remoteId,
      platformName,
      advertisedName,
      serviceUuids,
      rssi,
      connectable,
      txPower,
      manufacturerData,
    )
  }
}

/**
 * A role-tagged BLE link. The `pathId` is the only stable handle the
 * application should use to address a path. It has the form
 * `central:<opaque>` or `peripheral:<opaque>`. The portion after the colon
 * is the platform's view of the remote (CBPeripheral.identifier on iOS, the
 * Bluetooth address on Android) — treat it as opaque, do not parse it, and
 * do not assume it is stable across reconnects or app restarts.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class BlePath (
  val pathId: String,
  val role: BleRole,
  val state: BlePathState,
  val platformDeviceId: String? = null,
  val serviceUuid: String? = null,
  val characteristicUuid: String? = null,
  val rssi: Long,
  val mtu: Long,
  val canSend: Boolean,
  val error: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): BlePath {
      val pathId = list[0] as String
      val role = BleRole.ofRaw(list[1] as Int)!!
      val state = BlePathState.ofRaw(list[2] as Int)!!
      val platformDeviceId = list[3] as String?
      val serviceUuid = list[4] as String?
      val characteristicUuid = list[5] as String?
      val rssi = list[6].let { if (it is Int) it.toLong() else it as Long }
      val mtu = list[7].let { if (it is Int) it.toLong() else it as Long }
      val canSend = list[8] as Boolean
      val error = list[9] as String?
      return BlePath(pathId, role, state, platformDeviceId, serviceUuid, characteristicUuid, rssi, mtu, canSend, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      pathId,
      role.raw,
      state.raw,
      platformDeviceId,
      serviceUuid,
      characteristicUuid,
      rssi,
      mtu,
      canSend,
      error,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class BlePayload (
  val pathId: String,
  val role: BleRole,
  val value: ByteArray,
  val rssi: Long

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): BlePayload {
      val pathId = list[0] as String
      val role = BleRole.ofRaw(list[1] as Int)!!
      val value = list[2] as ByteArray
      val rssi = list[3].let { if (it is Int) it.toLong() else it as Long }
      return BlePayload(pathId, role, value, rssi)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      pathId,
      role.raw,
      value,
      rssi,
    )
  }
}
@Suppress("UNCHECKED_CAST")
private object GrassrootsBluetoothLayerHostApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleAdvertiseRequest.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleConnectRequest.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleDisconnectRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleInitializeOptions.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BlePath.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BlePath.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleScanRequest.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleSendRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BleAdvertiseRequest -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is BleConnectRequest -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is BleDisconnectRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is BleInitializeOptions -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is BlePath -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is BlePath -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is BleScanRequest -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is BleSendRequest -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface GrassrootsBluetoothLayerHostApi {
  fun initialize(options: BleInitializeOptions)
  fun isSupported(): Boolean
  fun adapterState(): BleAdapterState
  fun startAdvertising(request: BleAdvertiseRequest)
  fun stopAdvertising()
  fun startScan(request: BleScanRequest)
  fun stopScan()
  fun connect(request: BleConnectRequest): BlePath
  fun disconnect(request: BleDisconnectRequest)
  fun send(request: BleSendRequest)
  fun paths(): List<BlePath>
  fun dispose()

  companion object {
    /** The codec used by GrassrootsBluetoothLayerHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      GrassrootsBluetoothLayerHostApiCodec
    }
    /** Sets up an instance of `GrassrootsBluetoothLayerHostApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: GrassrootsBluetoothLayerHostApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.initialize", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as BleInitializeOptions
            var wrapped: List<Any?>
            try {
              api.initialize(optionsArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.isSupported", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.isSupported())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.adapterState", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.adapterState().raw)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.startAdvertising", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as BleAdvertiseRequest
            var wrapped: List<Any?>
            try {
              api.startAdvertising(requestArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.stopAdvertising", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.stopAdvertising()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.startScan", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as BleScanRequest
            var wrapped: List<Any?>
            try {
              api.startScan(requestArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.stopScan", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.stopScan()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.connect", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as BleConnectRequest
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.connect(requestArg))
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.disconnect", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as BleDisconnectRequest
            var wrapped: List<Any?>
            try {
              api.disconnect(requestArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.send", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as BleSendRequest
            var wrapped: List<Any?>
            try {
              api.send(requestArg)
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.paths", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              wrapped = listOf<Any?>(api.paths())
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerHostApi.dispose", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            var wrapped: List<Any?>
            try {
              api.dispose()
              wrapped = listOf<Any?>(null)
            } catch (exception: Throwable) {
              wrapped = wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object GrassrootsBluetoothLayerFlutterApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BleAdvertisement.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BlePath.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          BlePayload.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is BleAdvertisement -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is BlePath -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is BlePayload -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
class GrassrootsBluetoothLayerFlutterApi(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by GrassrootsBluetoothLayerFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      GrassrootsBluetoothLayerFlutterApiCodec
    }
  }
  fun onAdapterStateChanged(stateArg: BleAdapterState, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerFlutterApi.onAdapterStateChanged"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(stateArg.raw)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onAdvertisement(advertisementArg: BleAdvertisement, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerFlutterApi.onAdvertisement"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(advertisementArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onPathChanged(pathArg: BlePath, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerFlutterApi.onPathChanged"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(pathArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onPayloadReceived(payloadArg: BlePayload, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerFlutterApi.onPayloadReceived"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(payloadArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
  fun onLog(messageArg: String, callback: (Result<Unit>) -> Unit)
{
    val channelName = "dev.flutter.pigeon.grassroots_bluetooth_layer.GrassrootsBluetoothLayerFlutterApi.onLog"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(messageArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
